### PR TITLE
refactor: remove redundancy and improve clarity

### PR DESCRIPTION
**Pull request by RonaldTreur**
* consolidate `initializeCandidateSet` and `organizeVotesByNextCandidate` into one method: `getCandidateMapFromVoteRecords` (reducing redundancy)
* calculate `votesToRedistribute` earlier and pass that to `distributeVotes` instead of `quota` to  not force `eliminateLowestCandidate` to pass 0 just for the sake of calculations
* determine the `voteMultiplier` in the one place it is used: `redistributeToCandidates`, instead of earlier and passing it
* to improve consistency, use `newQuotaTotalVotes` throughout the codebase as the construct to communicate changes to the totalVotes
* streamline the code a bit (variable naming, using functions when they exist)

### CODE REVIEW

**Comment by YvesCandel** [comment]
Please update your branch with master so that we can see the unit test results

**Comment by RonaldTreur** [comment]
Hey folks!

Just checking in here. Is there anything you require from me to unblock this?
If you'd like me to make any changes, please let me know.
If you don't like the PR, that is also fine of course 👍

**Review by mindrunner — APPROVED** [review]
Looks good to me. Cleanup, no changes  in functionality.

**Comment by YvesCandel** [comment]
This pull request includes several changes to the `packages/stv` module, primarily focusing on refactoring and improving the handling of candidate maps and vote redistribution logic. The most important changes involve replacing the `initializeCandidateSet` function with `getCandidateMapFromVoteRecords`, updating test cases accordingly, and refining the vote redistribution process.

### Refactoring and Function Replacement:
* Replaced `initializeCandidateSet` with `getCandidateMapFromVoteRecords` in `calculateStvWinners` to initialize the candidate set with votes. (`packages/stv/src/index.ts`)
* Renamed and refactored the `initializeCandidateSet` function to `getCandidateMapFromVoteRecords`, improving clarity and consistency. (`packages/stv/src/index.ts`)

### Test Case Updates:
* Updated test cases to use `getCandidateMapFromVoteRecords` instead of `initializeCandidateSet`, ensuring they align with the new function. (`packages/stv/src/index.test.ts`)
* Removed the `organizeVotesByNextCandidate` test suite and integrated its logic into `getCandidateMapFromVoteRecords`. (`packages/stv/src/index.test.ts`)

### Vote Redistribution Logic:
* Modified the `distributeVotes` function to use `votesToRedistribute` instead of `quota` for redistributing votes. (`packages/stv/src/index.ts`)
* Updated the `redistributeExcessVotes` function to use `votesToRedistribute` and refactored to use `getCandidateMapFromVoteRecords` for organizing votes. (`packages/stv/src/index.ts`)

### Code Simplification:
* Simplified the calculation of the new quota in the `processElection` function by using the `calculateQuota` function. (`packages/stv/src/index.ts`)

These changes collectively enhance the clarity, maintainability, and functionality of the codebase, particularly in handling candidate maps and vote redistribution.

**Review by YvesCandel — APPROVED** [review]

**Pull request merged**
